name: Concurrency Demo

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  upload-tree:
    runs-on: ubuntu-latest
    name: Upload tree
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - run: |
          ls -larth >> list.txt
          echo "::group::Files list"
          cat list.txt
          echo "::endgroup::"
          
      - name: Uplload file
        uses: actions/upload-artifact@v4
        with:
          path: list.txt
          name: filelist

  add-summary:
    runs-on: ubuntu-latest
    needs:
      - upload-tree
    name: Add summary
    steps: 
      - name: Download file
        uses: actions/download-artifact@v4
        with:
          name: filelist
          
      - name: Add job summary with tree output
        run: |
          echo "### Job completed! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo '### Project Directory Tree' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat list.txt>> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      
